version: "3.9"

services:
  blog_service:
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    command: npm start
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
