version: '3.8'

services:
    blog_service:
        build: .
        ports:
            - ${PORT}:${PORT}
        restart: always
        command: npm start
        environment:
            - PORT=${PORT}
            - MONGO_URI=${MONGO_URI}
