version: '3.9'

services:
    blog_service:
        build: .
        ports:
            - ${port}:3000
        restart: always
        environment:
            - PORT=${port}
            - MONGO_URI=${mongo_uri}
            - MONGO_DB=${mongo_db}
            - MONGO_USER=${mongo_user}
            - MONGO_PASSWORD=${mongo_password}
            - JWT_SECRET=${jwt_secret}
