apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: ctse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: nodejs-app
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          image: redstreamdev/ctse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URI
