apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ctse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: mongo
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          image: mongo:7.0
          ports:
            - containerPort: 27017
